project_id = "wnlmeiqmjujjjesszgcg"

[functions.h2h]
verify_jwt = false

[functions.api-football]
verify_jwt = false

[functions.fixtures]
verify_jwt = false

[functions.livescore-sync]
verify_jwt = false

[functions.admin-fixtures]
verify_jwt = false

[functions.top-scorers]
verify_jwt = false